### ISSUE TITLE
Convert erb views to haml

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/mac_app#26]
Rewrite erb views in haml for consistency.

**Comment by BintLopez** [comment]
Halp! @kathrynemary 
![image](https://cloud.githubusercontent.com/assets/5728859/17354647/2370fb9c-5910-11e6-9e53-0aebf31ca8c9.png)

**Comment by kathrynemary** [comment]
Argh! I will work on that page tomorrow.

**Comment by MidwestAccessCoalition** [comment]
@kathrynemary many many thanks! =D

**Comment by kathrynemary** [comment]
For some reason I'm getting this after yesterday's commits. I had some
issues earlier due to an OSX upgrade, but I can't tell that this would be
caused by my computer's setup. Is it doing this for you too?

[image: Inline image 1]

**Comment by kathrynemary** [comment]
I'm on the last 2 files! However the on-call-times index is looking a little different than I envisioned.

<img width="900" alt="screen shot 2016-08-18 at 4 59 09 pm" src="https://cloud.githubusercontent.com/assets/8000996/17792208/26e26d04-6565-11e6-8d95-f1a86964ece4.png">
