### ISSUE TITLE
Might need to mess with on_call_times/_form

### ISSUE THREAD

**Issue by kathrynemary** [MidwestAccessCoalition/mac_app#53]
I'm not sure if the formatting just looks wonky to me, or if universal.

<img width="918" alt="screen shot 2016-08-15 at 6 34 21 pm" src="https://cloud.githubusercontent.com/assets/8000996/17683260/fc4eb1c4-6316-11e6-97d9-192a754b5561.png">
<img width="912" alt="screen shot 2016-08-15 at 6 34 39 pm" src="https://cloud.githubusercontent.com/assets/8000996/17683261/fe57f4e4-6316-11e6-89ce-d5026b1e7c41.png">

**Comment by BintLopez** [comment]
Def looks wonky. Would love you forever if you could give that some UI love!
